import {useMemo,useRef,useState} from 'react';
import {LayoutDashboard,FolderKanban,Wallet,TrendingUp,CalendarDays,ShieldAlert,FileText,ChevronRight,ArrowUpRight,ArrowDownRight,Search,Download,Upload,Layers,Menu,RotateCcw} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,LineChart,Line,Legend} from 'recharts';
import {demo,money,status,importSnapshots,exportCSV,type Portfolio,type Snapshot} from './data';
const views=['Resumen Ejecutivo','Cartera de Proyectos','Presupuesto','Avance Físico','Cronograma','Riesgos','Detalle de Proyecto'];
const icons=[LayoutDashboard,FolderKanban,Wallet,TrendingUp,CalendarDays,ShieldAlert,FileText];
const storageKey='dven-demo-v1';
function load():Portfolio{try{const raw=localStorage.getItem(storageKey);if(raw){const data=JSON.parse(raw);if(data.version===1&&JSON.stringify(data.projects)===JSON.stringify(demo.projects)&&Array.isArray(data.snapshots)){return importSnapshots(exportCSV(data.snapshots),{...demo,snapshots:[]});}}}catch{/* Invalid local cache falls back to demo. */}return demo;}
function download(content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='dven-demostracion.csv';a.click();URL.revokeObjectURL(url);}
export default function App(){const [portfolio,setPortfolio]=useState(load);const [view,setView]=useState(views[0]);const [month,setMonth]=useState('2026-06');const [query,setQuery]=useState('');const [area,setArea]=useState('Todas las áreas');const [signal,setSignal]=useState('Todos los estados');const [selected,setSelected]=useState('DV-001');const [notice,setNotice]=useState('');const [open,setOpen]=useState(false);const input=useRef<HTMLInputElement>(null);
const availableMonths=[...new Set(portfolio.snapshots.map(s=>s.month))].sort();
const rows=useMemo(()=>portfolio.projects.flatMap(p=>{const s=portfolio.snapshots.find(s=>s.projectId===p.id&&s.month===month);return s?[{...p,...s}]:[]}),[portfolio,month]);
const filtered=rows.filter(p=>(p.name+' '+p.id).toLowerCase().includes(query.toLowerCase())&&(area==='Todas las áreas'||p.area===area)&&(signal==='Todos los estados'||status(p)===signal));
const totals=rows.reduce((t,p)=>({capex:t.capex+p.capex,budget:t.budget+p.budget,actual:t.actual+p.actual,planned:t.planned+p.planned*p.budget,physical:t.physical+p.physical*p.budget}),{capex:0,budget:0,actual:0,planned:0,physical:0});
const planned=totals.budget?totals.planned/totals.budget:0,physical=totals.budget?totals.physical/totals.budget:0;
const critical=rows.filter(p=>status(p)==='Crítico');const risk=rows.filter(p=>p.reformulation);
const history=availableMonths.map(m=>{const cuts=portfolio.snapshots.filter(s=>s.month===m);const weight=cuts.reduce((n,s)=>n+s.budget,0);return {month:m.slice(5),Programado:weight?cuts.reduce((n,s)=>n+s.planned*s.budget,0)/weight:0,Real:weight?cuts.reduce((n,s)=>n+s.physical*s.budget,0)/weight:0};});
const project=portfolio.projects.find(p=>p.id===selected)!;const cut=rows.find(p=>p.id===selected);const ph=portfolio.snapshots.filter(s=>s.projectId===selected).sort((a,b)=>a.month.localeCompare(b.month)).map(s=>({month:s.month,Programado:s.planned,Real:s.physical}));
function navigate(v:string){setView(v);setOpen(false);}function detail(id:string){setSelected(id);navigate(views[6]);}function persist(next:Portfolio){localStorage.setItem(storageKey,JSON.stringify(next));setPortfolio(next);}
async function upload(file?:File){if(!file)return;try{if(file.size>2_000_000)throw new Error('Máximo 2 MB por archivo');const next=importSnapshots(await file.text(),portfolio);persist(next);setNotice('Cortes importados. Historial guardado en este navegador.');}catch(e){setNotice(e instanceof Error?e.message:'No se pudo importar');}if(input.current)input.current.value='';}
const badge=(s:Snapshot)=><span className={'badge '+(status(s)==='Crítico'?'red':status(s)==='Atención'?'amber':'green')}><i/>{status(s)}</span>;
const chart=(data:object[],line=false)=><ResponsiveContainer width="100%" height={260}>{line?<LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis unit="%" domain={[0,100]}/><Tooltip formatter={v=>`${Number(v).toFixed(1)}%`}/><Legend/><Line dataKey="Programado" stroke="#a5b4bc" strokeDasharray="5 5" dot={false}/><Line dataKey="Real" stroke="#1c8870" strokeWidth={3}/></LineChart>:<BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="id"/><YAxis width={60}/><Tooltip formatter={v=>`${money(Number(v))} MM$`}/><Legend/><Bar dataKey="budget" name="Presupuesto anual" fill="#cfddd8" radius={[4,4,0,0]}/><Bar dataKey="actual" name="Gasto acumulado" fill="#218c73" radius={[4,4,0,0]}/></BarChart>}</ResponsiveContainer>;
const table=()=> <div className="table-wrap"><table><thead><tr><th>Proyecto / responsable</th><th>Área</th><th>Presupuesto anual</th><th>Gasto acumulado</th><th>Avance físico</th><th>Estado</th><th/></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><button className="project-link" onClick={()=>detail(p.id)}>{p.name}</button><small>{p.id} · {p.owner}</small></td><td>{p.area}</td><td>{money(p.budget)} <small>MM$</small></td><td>{money(p.actual)} <small>MM$</small></td><td><div className="progress"><span style={{width:p.physical+'%'}}/></div>{p.physical.toFixed(1)}% <small> / {p.planned.toFixed(1)}% prog.</small></td><td>{badge(p)}</td><td><button aria-label={'Ver '+p.name} onClick={()=>detail(p.id)}><ChevronRight size={18}/></button></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">No hay proyectos con estos filtros y corte mensual.</p>}</div>;
return <div className="app"><aside className={open?'sidebar visible':'sidebar'}><div className="brand"><div className="brand-icon"><Layers/></div><div>DVEN<span>GESTIÓN DE INVERSIONES</span></div></div><div className="workspace-label">ESPACIO EJECUTIVO</div><nav>{views.map((v,i)=>{const Icon=icons[i];return <button key={v} onClick={()=>navigate(v)} className={view===v?'active':''}><Icon size={19}/>{v}{view===v&&<span className="nav-dot"/>}</button>})}</nav><div className="sidebar-bottom"><div className="demo-dot"/>ENTORNO DE DEMOSTRACIÓN<p>Datos simulados · Sin información corporativa</p></div><div className="profile"><div>DE</div><span>Dirección Ejecutiva<small>Vista de demostración</small></span></div></aside><main><header><div className="breadcrumb"><button className="mobile-menu" aria-label="Abrir menú" onClick={()=>setOpen(!open)}><Menu/></button>Cartera de inversiones <ChevronRight size={14}/><strong>{view}</strong></div><span className="top-demo">DATOS FICTICIOS</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">MONITOREO DE CARTERA / 2026</div><h1>{view}</h1><p>Una visión integrada para decisiones de inversión.</p></div><div className="month-picker"><CalendarDays size={18}/><label htmlFor="month">Corte mensual</label><select id="month" value={month} onChange={e=>setMonth(e.target.value)}>{availableMonths.map(m=><option key={m} value={m}>{new Date(m+'-02T12:00:00').toLocaleDateString('es-CL',{month:'long',year:'numeric'})}</option>)}</select></div></div><div className="demo-banner"><ShieldAlert size={17}/><span><strong>Demostración.</strong> Todos los proyectos, cifras y responsables son ficticios. Importa solo datos de prueba.</span></div>
{view===views[0]&&<><div className="section-label">PULSO DE LA CARTERA <span>{rows.length} proyectos con corte · Valores en millones de CLP</span></div><div className="kpi-grid">{[['CAPEX total',money(totals.capex),'Inversión total de los proyectos'],['Presupuesto anual',money(totals.budget),'Asignación del año 2026'],['Gasto real acumulado',money(totals.actual),`${totals.budget?(totals.actual/totals.budget*100).toFixed(1):0}% del presupuesto anual`],['Avance físico real',physical.toFixed(1)+'%',`Programado: ${planned.toFixed(1)}%`],['Proyectos críticos',String(critical.length),'Desviación mayor a 10 puntos'],['Riesgo de reformulación',String(risk.length),'Proyectos con alerta de revisión']].map(([label,value,caption],i)=><div className={'kpi kpi-'+i} key={label}><div>{label}{i>3?<ShieldAlert size={18}/>:<ArrowUpRight size={18}/>}</div><strong>{value}{i<3&&<small> MM$</small>}</strong><p>{i===3&&<ArrowDownRight size={14}/>} {caption}</p></div>)}</div><div className="chart-grid"><section className="card"><div className="card-title"><div><h2>Ejecución presupuestaria</h2><p>Presupuesto anual vs. gasto acumulado · MM$</p></div><Wallet size={20}/></div>{chart(rows)}</section><section className="card"><div className="card-title"><div><h2>Evolución del avance físico</h2><p>Promedio ponderado por presupuesto anual</p></div><TrendingUp size={20}/></div>{chart(history,true)}</section></div></>}
{[views[0],views[1],views[2],views[3]].includes(view)&&<section className="card portfolio-card"><div className="card-title"><div><h2>{view===views[0]?'Proyectos de la cartera':view}</h2><p>Consulta el estado y abre el detalle de cada inversión.</p></div><span className="count">{filtered.length} proyectos</span></div><div className="filters"><div className="search"><Search size={17}/><input aria-label="Buscar proyecto" placeholder="Buscar por proyecto o código…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrar área" value={area} onChange={e=>setArea(e.target.value)}>{['Todas las áreas',...new Set(portfolio.projects.map(p=>p.area))].map(a=><option key={a}>{a}</option>)}</select><select aria-label="Filtrar estado" value={signal} onChange={e=>setSignal(e.target.value)}>{['Todos los estados','En línea','Atención','Crítico'].map(s=><option key={s}>{s}</option>)}</select></div>{view===views[2]&&chart(filtered)}{view===views[3]&&<div className="physical-list">{filtered.map(p=><div key={p.id}><button onClick={()=>detail(p.id)}>{p.name}</button><div className="progress"><span style={{width:p.physical+'%'}}/></div><span>Real {p.physical.toFixed(1)}% · Programado {p.planned.toFixed(1)}%</span></div>)}</div>}{table()}</section>}
{view===views[4]&&<section className="card"><div className="card-title"><div><h2>Horizonte de ejecución</h2><p>Fechas planificadas ficticias · enero 2026 a junio 2027</p></div></div><div className="timeline">{portfolio.projects.map(p=>{const index=(s:string)=>(Number(s.slice(0,4))-2026)*12+Number(s.slice(5))-1;return <div className="timeline-row" key={p.id}><button onClick={()=>detail(p.id)}>{p.name}<small>{p.start} → {p.end}</small></button><div className="timeline-track"><span style={{left:index(p.start)/18*100+'%',width:(index(p.end)-index(p.start)+1)/18*100+'%'}}>{p.id}</span></div></div>})}</div></section>}
{view===views[5]&&<section className="card"><div className="card-title"><div><h2>Registro de riesgos</h2><p>Semáforo calculado por desviación física; reformulación declarada por corte.</p></div></div><div className="risk-grid">{rows.map(p=><article key={p.id} className="risk-item">{badge(p)}<h3><button onClick={()=>detail(p.id)}>{p.name}</button></h3><p>{p.risk}</p><small>Responsable: {p.owner}</small><p className={p.reformulation?'risk-alert':''}>{p.reformulation?'Requiere revisión de reformulación':'Sin alerta de reformulación'}</p><small>Acción de demostración: revisar plan de mitigación en comité mensual.</small></article>)}</div></section>}
{view===views[6]&&<><div className="detail-navigation"><label htmlFor="project">Proyecto</label><select id="project" value={selected} onChange={e=>setSelected(e.target.value)}>{portfolio.projects.map(p=><option key={p.id} value={p.id}>{p.id} · {p.name}</option>)}</select><button aria-label="Proyecto anterior" onClick={()=>setSelected(portfolio.projects[(portfolio.projects.findIndex(p=>p.id===selected)+portfolio.projects.length-1)%portfolio.projects.length].id)}>←</button><button aria-label="Proyecto siguiente" onClick={()=>setSelected(portfolio.projects[(portfolio.projects.findIndex(p=>p.id===selected)+1)%portfolio.projects.length].id)}>→</button></div><section className="card"><div className="card-title"><div><div className="eyebrow">{project.id} / {project.area}</div><h2>{project.name}</h2><p>{project.owner} · Plan {project.start} a {project.end}</p></div>{cut&&badge(cut)}</div>{cut?<div className="detail-stats"><div>CAPEX<strong>{money(project.capex)} MM$</strong></div><div>Presupuesto anual<strong>{money(cut.budget)} MM$</strong></div><div>Gasto real<strong>{money(cut.actual)} MM$</strong></div><div>Avance real / plan<strong>{cut.physical.toFixed(1)}% / {cut.planned.toFixed(1)}%</strong></div></div>:<p className="empty">Este proyecto no tiene datos para el corte seleccionado.</p>}<h3>Historial mensual del proyecto</h3>{chart(ph,true)}<p><strong>Riesgo identificado:</strong> {project.risk}</p></section></>}
<section className="data-tools"><div><h3>Datos de demostración</h3><p>Historial mensual local · Importación CSV por proyecto y mes</p></div><div className="tool-buttons"><button onClick={()=>download(exportCSV(portfolio.snapshots))}><Download size={16}/>Exportar CSV / plantilla</button><button onClick={()=>input.current?.click()}><Upload size={16}/>Importar CSV</button><button onClick={()=>{if(window.confirm('¿Restablecer los datos ficticios? Se eliminarán los cortes importados de este navegador.')){try{persist(demo);setMonth('2026-06');setNotice('Datos ficticios restablecidos.');}catch{setNotice('No se pudo guardar en el navegador.');}}}}><RotateCcw size={16}/>Restablecer</button><input ref={input} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/></div></section>{notice&&<p role="status" className="notice">{notice}</p>}<footer><span>DVEN · Dashboard Ejecutivo</span><span>Datos ficticios · Sin conexión a sistemas corporativos</span></footer></div></main></div>;
}
