export interface Project {id:string; name:string; area:string; owner:string; capex:number; start:string; end:string; risk:string}
export interface Snapshot {projectId:string; month:string; budget:number; actual:number; planned:number; physical:number; reformulation:boolean}
export interface Portfolio {version:1; projects:Project[]; snapshots:Snapshot[]}
export const months=['2026-01','2026-02','2026-03','2026-04','2026-05','2026-06'];
export const projects:Project[]=[
{id:'DV-001',name:'Ampliación Planta Norte',area:'Infraestructura',owner:'Equipo Alfa',capex:42000,start:'2026-01',end:'2027-06',risk:'Retraso en suministro de equipos'},
{id:'DV-002',name:'Sistema de Impulsión',area:'Operaciones',owner:'Equipo Beta',capex:28500,start:'2026-01',end:'2026-12',risk:'Disponibilidad de contratistas'},
{id:'DV-003',name:'Parque Solar Horizonte',area:'Energía',owner:'Equipo Gamma',capex:36000,start:'2026-02',end:'2027-03',risk:'Permisos ambientales pendientes'},
{id:'DV-004',name:'Modernización de Control',area:'Tecnología',owner:'Equipo Delta',capex:12800,start:'2026-01',end:'2026-10',risk:'Integración con sistemas existentes'},
{id:'DV-005',name:'Centro Logístico Sur',area:'Infraestructura',owner:'Equipo Épsilon',capex:21500,start:'2026-03',end:'2027-02',risk:'Variación de precios de materiales'},
{id:'DV-006',name:'Red de Agua Industrial',area:'Operaciones',owner:'Equipo Zeta',capex:18200,start:'2026-01',end:'2026-11',risk:'Interferencia con instalaciones'}];
export const demo:Portfolio={version:1,projects,snapshots:months.flatMap((month,m)=>projects.map((p,i)=>({projectId:p.id,month,budget:[18000,16000,14000,9500,11000,12000][i],actual:Math.round([16000,14500,11000,9000,8200,11800][i]*(m+1)/6),planned:Math.min(95,[65,80,45,90,40,75][i]*(m+1)/6),physical:Math.min(100,[58,62,32,93,38,59][i]*(m+1)/6),reformulation:i===2||i===5}))) }; // All amounts are fictional, in millions of CLP; spend is YTD.
export function status(s:Snapshot){return s.physical-s.planned < -10?'Crítico':s.physical-s.planned < -5?'Atención':'En línea'}
export const money=(n:number)=>new Intl.NumberFormat('es-CL',{maximumFractionDigits:0}).format(n);
// RFC-style quoted fields, embedded newlines and escaped quotes are supported.
export function parseCSV(text:string):string[][]{const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else if(quoted){quoted=false;}else if(field===''){quoted=true;}else throw new Error('Comillas inválidas en CSV');}else if(!quoted&&(c===','||c==='\n'||c==='\r')){row.push(field);field='';if(c!==','){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(x=>x!==''))rows.push(row);row=[];}}else field+=c;}if(quoted)throw new Error('Campo CSV sin cierre de comillas');if(field!==''||row.length){row.push(field);rows.push(row);}return rows;}
export const csvHeader='projectId,month,budget,actual,planned,physical,reformulation';
export function importSnapshots(text:string,portfolio:Portfolio):Portfolio{const rows=parseCSV(text.replace(/^\uFEFF/,''));if(rows.shift()?.join(',')!==csvHeader)throw new Error('Cabecera inválida. Descarga la plantilla.');if(!rows.length)throw new Error('El archivo no contiene registros');const keys=new Set<string>();const incoming=rows.map((r,i):Snapshot=>{if(r.length!==7)throw new Error(`Fila ${i+2}: se esperan 7 columnas`);const [projectId,month,b,a,p,f,flag]=r;const values=[b,a,p,f].map(Number);if(!portfolio.projects.some(x=>x.id===projectId)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||[b,a,p,f].some(x=>!x.trim())||values.some(x=>!Number.isFinite(x)||x<0)||values[2]>100||values[3]>100||!['true','false'].includes(flag))throw new Error(`Fila ${i+2}: proyecto, mes o valores inválidos`);const key=projectId+month;if(keys.has(key))throw new Error(`Fila ${i+2}: corte mensual duplicado`);keys.add(key);return {projectId,month,budget:values[0],actual:values[1],planned:values[2],physical:values[3],reformulation:flag==='true'};});return {...portfolio,snapshots:[...portfolio.snapshots.filter(s=>!keys.has(s.projectId+s.month)),...incoming]};}
export function exportCSV(snapshots:Snapshot[]){return csvHeader+'\n'+snapshots.map(s=>[s.projectId,s.month,s.budget,s.actual,s.planned,s.physical,s.reformulation].join(',')).join('\n');}
