import {useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,XAxis,YAxis,Tooltip,Legend,CartesianGrid} from 'recharts';
import {readWorkbook,type ApisProject} from './excel';
import {flashMonth,parseFlash,mergeFlash,flashStatus,reformulation,flashTotals,type FlashCut} from './flash';
const key='dven-flash-v1';
export function loadFlash():FlashCut[]{try{const raw=JSON.parse(sessionStorage.getItem(key)||'[]');return Array.isArray(raw)?raw:[];}catch{return [];}}
const fmt=(v:number|null)=>v===null?'Sin datos':v.toLocaleString('es-CL',{maximumFractionDigits:1});
export default function FlashPanel({projects,view,selected,history,onHistory}:{projects:ApisProject[];view:string;selected:string;history:FlashCut[];onHistory:(cuts:FlashCut[])=>void}){const [sheets,setSheets]=useState<Awaited<ReturnType<typeof readWorkbook>>>([]);const [sheet,setSheet]=useState('');const [importMonth,setImportMonth]=useState('');const [preview,setPreview]=useState<FlashCut[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [month,setMonth]=useState('');const [query,setQuery]=useState('');const [signal,setSignal]=useState('Todos');
const months=[...new Set(history.map(s=>s.month))].sort();const active=months.includes(month)?month:months.at(-1)||'';const rows=history.filter(s=>s.month===active);const filtered=rows.filter(s=>(s.code+' '+s.name).toLowerCase().includes(query.toLowerCase())&&(signal==='Todos'||flashStatus(s)===signal));const totals=flashTotals(rows);const badge=(s:FlashCut)=><span className={'badge '+(flashStatus(s)==='Crítico'?'red':flashStatus(s)==='Atención'?'amber':'green')}>{flashStatus(s)}</span>;
function inspect(name:string,m:string,list=sheets){setSheet(name);setImportMonth(m);setPreview([]);try{setPreview(parseFlash(list.find(s=>s.name===name)!.rows,m));setMessage('Vista previa validada. Importes en KUSD.');}catch(e){setMessage((e as Error).message);}}
async function upload(file?:File){if(!file)return;setBusy(true);setPreview([]);setSheets([]);try{if(!/\.xlsx$/i.test(file.name)||file.size>10_000_000)throw Error('Selecciona un .xlsx de máximo 10 MB');const next=await readWorkbook(await file.arrayBuffer(),34);if(!next.length)throw Error('Libro sin hojas');setSheets(next);inspect(next[0].name,flashMonth(next[0].rows),next);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
function apply(){try{const next=mergeFlash(history,preview);sessionStorage.setItem(key,JSON.stringify(next));onHistory(next);setMonth(importMonth);setPreview([]);setMessage('Corte Flash guardado. Los demás meses se conservaron.');}catch{setMessage('No se pudo guardar. Se conserva el historial anterior.');}}
const series=months.map(m=>{const total=flashTotals(history.filter(s=>s.month===m));return {month:m,Programado:total.planned,Real:total.physical};});
const detailRows=history.filter(s=>s.code===selected).sort((a,b)=>a.month.localeCompare(b.month));
function exportHistory(){const fields=Object.keys(history[0]||{});if(!fields.length)return;const quote=(v:unknown)=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[fields.join(','),...history.map(s=>fields.map(f=>quote(s[f as keyof FlashCut])).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='historial-flash-kusd.csv';a.click();URL.revokeObjectURL(url);}
return <><section className="card"><h2>Cargar Excel Flash · KUSD</h2><p className="import-help">Importa A–AH según la estructura Flash. Cada API se vincula por código; una recarga reemplaza el mismo proyecto y mes, conservando otros cortes.</p><label className="excel-upload">{busy?'Leyendo Flash…':'Seleccionar Excel Flash'}<input aria-label="Seleccionar Excel Flash" type="file" accept=".xlsx" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label>{sheets.length>0&&<div className="detail-navigation"><label>Hoja <select aria-label="Hoja Flash" value={sheet} onChange={e=>{const name=e.target.value;inspect(name,flashMonth(sheets.find(s=>s.name===name)!.rows));}}>{sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Mes de control <input aria-label="Mes a importar Flash" type="month" value={importMonth} onChange={e=>inspect(sheet,e.target.value)}/></label></div>}{preview.length>0&&<><p className="import-help">{preview.length} proyectos · {importMonth} · {preview.filter(s=>!projects.some(p=>p.code===s.code)).length} sin ficha APIS. Vista previa de hasta 10 registros.</p><div className="table-wrap"><table><thead><tr><th>API</th><th>Presupuesto anual KUSD</th><th>Gasto acumulado KUSD</th><th>Físico prog. / real</th></tr></thead><tbody>{preview.slice(0,10).map(s=><tr key={s.code}><td>{s.code}</td><td>{fmt(s.annualBudget)}</td><td>{fmt(s.ytdSpend)}</td><td>{fmt(s.planned)}% / {fmt(s.physical)}%</td></tr>)}</tbody></table></div><button className="apply-import" onClick={apply}>Confirmar corte {importMonth}</button></>}{message&&<p role="status" className="notice">{message}</p>}</section>
{history.length>0&&<><div className="detail-navigation"><label>Corte Flash <select aria-label="Corte mensual Flash" value={active} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m}>{m}</option>)}</select></label><button onClick={exportHistory}>Exportar historial CSV</button><button onClick={()=>{if(confirm('¿Eliminar todos los cortes Flash de esta sesión?')){sessionStorage.removeItem(key);onHistory([]);}}}>Eliminar historial Flash</button></div>
{view==='Resumen Ejecutivo'&&<><div className="kpi-grid">{[['CAPEX APIS',fmt(projects.length?projects.reduce((n,p)=>n+p.capex,0):null)+' KUSD',`${projects.length} fichas APIS`],['Total API programado Flash',fmt(totals.api.value)+' KUSD',`${totals.api.count}/${rows.length} proyectos con monto`],['Presupuesto anual',fmt(totals.budget.value)+' KUSD',`${totals.budget.count}/${rows.length} proyectos con dato`],['Gasto real acumulado',fmt(totals.spend.value)+' KUSD',`${totals.spend.count}/${rows.length} proyectos con dato`],['Avance físico programado / real',`${fmt(totals.planned)}% / ${fmt(totals.physical)}%`,`${totals.physicalCount}/${rows.length} proyectos ponderados por presupuesto anual`],['Críticos / alerta de reformulación',`${rows.filter(s=>flashStatus(s)==='Crítico').length} / ${rows.filter(s=>reformulation(s)===true).length}`,'Alerta por fecha proyectada > máximo sin reformular']].map(([label,value,caption])=><div className="kpi" key={label}><div>{label}</div><strong>{value}</strong><p>{caption}</p></div>)}</div><section className="card"><h2>Evolución física · Historial Flash</h2><p className="import-help">Promedio ponderado por presupuesto anual. Cada corte refleja su cobertura disponible.</p><ResponsiveContainer width="100%" height={260}><LineChart data={series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Legend/><Line dataKey="Programado" stroke="#98ada3"/><Line dataKey="Real" stroke="#218c73"/></LineChart></ResponsiveContainer></section></>}
{view==='Presupuesto'&&<section className="card"><h2>Presupuesto anual y gasto acumulado · KUSD</h2><ResponsiveContainer width="100%" height={280}><BarChart data={filtered}><XAxis dataKey="code"/><YAxis/><Tooltip/><Legend/><Bar dataKey="annualBudget" name="Presupuesto anual" fill="#a6bfb1"/><Bar dataKey="ytdSpend" name="Gasto acumulado" fill="#218c73"/></BarChart></ResponsiveContainer></section>}
{['Resumen Ejecutivo','Cartera de Proyectos','Presupuesto','Avance Físico','Cronograma','Riesgos'].includes(view)&&<section className="card"><h2>Control Flash · {active}</h2><div className="filters"><input className="search" aria-label="Buscar Flash" placeholder="Buscar código o nombre" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Semáforo Flash" value={signal} onChange={e=>setSignal(e.target.value)}>{['Todos','En línea','Atención','Crítico','Sin datos'].map(s=><option key={s}>{s}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>API / nombre</th>{view==='Cronograma'?<><th>Inicio</th><th>Término autorizado</th><th>Real / proyectado</th><th>Máximo sin reformular</th></>:<><th>Presupuesto anual KUSD</th><th>Gasto acumulado KUSD</th><th>Avance prog. / real</th><th>Estado</th></>}<th>Reformulación por fecha</th></tr></thead><tbody>{filtered.map(s=><tr key={s.code}><td>{s.name}<small>{s.code} · {s.owner}</small>{!projects.some(p=>p.code===s.code)&&<small>Pendiente de ficha APIS</small>}</td>{view==='Cronograma'?<><td>{s.start||'Sin datos'}</td><td>{s.end||'Sin datos'}</td><td>{s.forecastEnd||'Sin datos'}</td><td>{s.maxEnd||'Sin datos'}</td></>:<><td>{fmt(s.annualBudget)}</td><td>{fmt(s.ytdSpend)}</td><td>{fmt(s.planned)}% / {fmt(s.physical)}%</td><td>{badge(s)}</td></>}<td>{reformulation(s)===null?'Sin datos':reformulation(s)?'Alerta':'Sin alerta'}</td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">Sin registros para estos filtros.</p>}</div><p className="import-help">Semáforo físico: crítico si real − programado &lt; −10 puntos; atención si &lt; −5. Los valores vacíos se mantienen como sin datos. La alerta de fecha no sustituye una evaluación formal de reformulación.</p></section>}
{view==='Detalle de Proyecto'&&<section className="card"><h2>Historial Flash · {selected||'Selecciona un proyecto'}</h2><div className="table-wrap"><table><thead><tr><th>Mes</th><th>Total APIS KUSD</th><th>Total API Flash prog. / proy. KUSD</th><th>Presupuesto anual KUSD</th><th>Gasto acumulado KUSD</th><th>Avance prog. / real</th><th>Gasto del mes KUSD</th></tr></thead><tbody>{detailRows.map(s=><tr key={s.month}><td>{s.month}</td><td>{fmt(projects.find(p=>p.code===selected)?.capex??null)}</td><td>{fmt(s.apiPlanned)} / {fmt(s.apiForecast)}</td><td>{fmt(s.annualBudget)}</td><td>{fmt(s.ytdSpend)}</td><td>{fmt(s.planned)}% / {fmt(s.physical)}%</td><td>{fmt(s.monthlySpend)}</td></tr>)}</tbody></table>{!detailRows.length&&<p className="empty">Sin cortes Flash para este proyecto.</p>}</div></section>}
</>}
</>;
}
