import {parseAmount} from './excel';
export interface FlashCut {code:string;name:string;owner:string;controller:string;justification:string;decision:string;stage:string;month:string;apiPlanned:number|null;apiForecast:number|null;totalSpend:number|null;totalPhysical:number|null;annualBudget:number|null;annualForecast:number|null;annualPlannedPhysical:number|null;annualForecastPhysical:number|null;ytdBudget:number|null;ytdSpend:number|null;planned:number|null;physical:number|null;monthlyBudget:number|null;monthlySpend:number|null;monthlyPlanned:number|null;monthlyPhysical:number|null;start:string|null;end:string|null;forecastEnd:string|null;maxEnd:string|null}
const clean=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
const empty=(v:unknown)=>v==null||String(v).trim()==='';
export function flashMonth(rows:unknown[][]):string{for(const r of rows){const index=r.findIndex(v=>clean(v)==='mes de control');if(index>=0){const v=r[index+1];if(v instanceof Date)return v.toISOString().slice(0,7);const s=clean(v);if(/^\d{4}-(0[1-9]|1[0-2])$/.test(s))return s;const match=s.match(/^(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)[- /](\d{2}|\d{4})$/);if(match){const m=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'].indexOf(match[1])+1;return `${match[2].length===2?'20'+match[2]:match[2]}-${String(m).padStart(2,'0')}`;}}}return '';}
export function flashDate(v:unknown):string|null{if(empty(v))return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString().slice(0,10);if(typeof v==='number'&&Number.isFinite(v))return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const text=String(v).trim();const m=text.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);const iso=m?`${m[3]}-${m[2]}-${m[1]}`:text;if(!/^\d{4}-\d{2}-\d{2}$/.test(iso)||Number.isNaN(Date.parse(iso))||new Date(iso).toISOString().slice(0,10)!==iso)throw Error('Fecha inválida (usa DD-MM-YYYY)');return iso;}
function percentage(v:unknown):number|null{if(empty(v))return null;let n:number;if(typeof v==='number')n=v*100;else n=Number(String(v).replace(/\s|%/g,'').replace(',','.'));if(!Number.isFinite(n)||n<0||n>100)throw Error('Avance fuera del rango 0–100%');return n;}
export function parseFlash(rows:unknown[][],month:string):FlashCut[]{if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('Selecciona el mes de control');const header=rows.findIndex(r=>clean(r[0])==='api'&&clean(r[1])==='nombre'&&clean(r[7])==='prog'&&clean(r[30])==='inicio api'&&clean(r[33])==='termino max (sin reformular)');if(header<0)throw Error('No se reconoce la estructura Flash A–AH (API, Nombre, Prog y fechas finales).');const seen=new Set<string>();const cuts:FlashCut[]=[];rows.slice(header+1).forEach((r,i)=>{if(empty(r[0])||/^total(?:es)?\b/i.test(String(r[0]).trim()))return;try{const text=(n:number)=>String(r[n]??'').trim();const amount=(n:number)=>empty(r[n])?null:parseAmount(typeof r[n]==='string'?String(r[n]).replace(/\$/g,''):r[n]);const code=text(0);if(!/^[A-Za-z0-9_-]+$/.test(code)||!text(1))throw Error('Código o nombre inválido');if(seen.has(code))throw Error(`API duplicado: ${code}`);seen.add(code);cuts.push({code,name:text(1),owner:text(2),controller:text(3),justification:text(4),decision:text(5),stage:text(6),month,apiPlanned:amount(7),apiForecast:amount(8),totalSpend:amount(10),totalPhysical:percentage(r[11]),annualBudget:amount(12),annualForecast:amount(13),annualPlannedPhysical:percentage(r[15]),annualForecastPhysical:percentage(r[16]),ytdBudget:amount(18),ytdSpend:amount(19),planned:percentage(r[21]),physical:percentage(r[22]),monthlyBudget:amount(24),monthlySpend:amount(25),monthlyPlanned:percentage(r[27]),monthlyPhysical:percentage(r[28]),start:flashDate(r[30]),end:flashDate(r[31]),forecastEnd:flashDate(r[32]),maxEnd:flashDate(r[33])});}catch(e){throw Error(`Fila ${header+i+2}: ${(e as Error).message}`);}});if(!cuts.length)throw Error('No hay proyectos Flash válidos');return cuts;}
export function mergeFlash(history:FlashCut[],incoming:FlashCut[]){const keys=new Set(incoming.map(s=>s.code+'|'+s.month));return [...history.filter(s=>!keys.has(s.code+'|'+s.month)),...incoming].sort((a,b)=>a.month.localeCompare(b.month)||a.code.localeCompare(b.code));}
export function flashStatus(s:FlashCut){if(s.planned===null||s.physical===null)return 'Sin datos';const delta=s.physical-s.planned;return delta< -10?'Crítico':delta< -5?'Atención':'En línea';}
export function reformulation(s:FlashCut):boolean|null{return s.forecastEnd&&s.maxEnd?s.forecastEnd>s.maxEnd:null;}
export function flashTotals(cuts:FlashCut[]){const sum=(field:keyof FlashCut)=>{const numbers=cuts.map(s=>s[field]).filter((v):v is number=>typeof v==='number');return {value:numbers.length?numbers.reduce((n,v)=>n+v,0):null,count:numbers.length};};const valid=cuts.filter(s=>s.annualBudget!==null&&s.annualBudget>0&&s.planned!==null&&s.physical!==null);const weight=valid.reduce((n,s)=>n+s.annualBudget!,0);return {budget:sum('annualBudget'),spend:sum('ytdSpend'),api:sum('apiPlanned'),planned:weight?valid.reduce((n,s)=>n+s.planned!*s.annualBudget!,0)/weight:null,physical:weight?valid.reduce((n,s)=>n+s.physical!*s.annualBudget!,0)/weight:null,physicalCount:valid.length};}
