import {useState} from 'react';
import {Upload,Layers,ArrowLeft,Trash2} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {parseApis,readWorkbook,type ApisProject} from './excel';
const key='dven-apis-v1';
export default function RealDashboard({onDemo}:{onDemo:()=>void}){const [projects,setProjects]=useState<ApisProject[]>(()=>{try{return JSON.parse(sessionStorage.getItem(key)||'[]');}catch{return [];}});const [sheets,setSheets]=useState<Awaited<ReturnType<typeof readWorkbook>>>([]);const [sheet,setSheet]=useState('');const [preview,setPreview]=useState<ApisProject[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [view,setView]=useState('Resumen Ejecutivo');const [query,setQuery]=useState('');const [area,setArea]=useState('');const [selected,setSelected]=useState('');const [fileName,setFileName]=useState('');
const views=['Resumen Ejecutivo','Cartera de Proyectos','Presupuesto','Avance Físico','Cronograma','Riesgos','Detalle de Proyecto'];
const filtered=projects.filter(p=>(p.code+' '+p.name).toLowerCase().includes(query.toLowerCase())&&(!area||p.area===area));const total=projects.reduce((n,p)=>n+p.capex,0);const fmt=(v:number)=>v.toLocaleString('es-CL',{maximumFractionDigits:2});const project=projects.find(p=>p.code===selected);
function inspect(name:string,list=sheets){setSheet(name);setPreview([]);try{setPreview(parseApis(list.find(s=>s.name===name)!.rows));setMessage('Vista previa validada. Confirma la carga para reemplazar la cartera importada.');}catch(e){setMessage((e as Error).message);}}
async function upload(file?:File){if(!file)return;setBusy(true);setPreview([]);setSheets([]);setMessage('');try{if(!/\.xlsx$/i.test(file.name))throw new Error('Carga un archivo .xlsx. Para .xls, guarda una copia como .xlsx en Excel.');if(file.size>10_000_000)throw new Error('El archivo supera el máximo de 10 MB');const result=await readWorkbook(await file.arrayBuffer());if(!result.length)throw new Error('Libro sin hojas');setSheets(result);setFileName(file.name);inspect(result[0].name,result);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
function apply(){try{sessionStorage.setItem(key,JSON.stringify(preview));setProjects(preview);setSelected(preview[0].code);setPreview([]);setMessage('Cartera actualizada con APIS. Datos guardados solo en esta sesión del navegador.');}catch{setMessage('No hay espacio para guardar la cartera. La carga no se aplicó.');}}
return <div className="app"><aside className="sidebar real-sidebar"><div className="brand"><Layers/>DVEN</div><div className="workspace-label">DATOS IMPORTADOS · APIS</div><nav>{views.map(v=><button className={v===view?'active':''} key={v} onClick={()=>setView(v)}>{v}</button>)}</nav><button className="back-demo" onClick={onDemo}><ArrowLeft size={16}/> Volver a demostración</button></aside><main><header><strong>Dashboard Ejecutivo DVEN</strong><span className="top-demo">DATOS IMPORTADOS</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">CARTERA APIS / COLUMNAS A–L</div><h1>{view}</h1><p>Montos originales en miles de dólares (KUSD).</p></div></div><div className="demo-banner">Los datos importados se procesan en tu navegador y no se envían a GitHub, Vercel ni a un servidor. No se mezclan con la demostración.</div><section className="card"><h2>Cargar archivo Excel APIS</h2><p className="import-help">Selecciona el archivo .xlsx, elige su hoja y revisa la vista previa. Cada carga reemplaza los datos maestros de la cartera. No importa las columnas posteriores a L.</p><label className="excel-upload"><Upload size={18}/><span>{busy?'Leyendo Excel…':'Seleccionar Excel'}</span><input aria-label="Seleccionar Excel APIS" type="file" accept=".xlsx" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label>{sheets.length>0&&<div className="detail-navigation"><span>{fileName}</span><label htmlFor="sheet">Hoja</label><select id="sheet" value={sheet} onChange={e=>inspect(e.target.value)}>{sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></div>}{preview.length>0&&<><p className="import-help">{preview.length} proyectos · CAPEX total {fmt(preview.reduce((n,p)=>n+p.capex,0))} KUSD</p><div className="table-wrap"><table><thead><tr><th>Código</th><th>Nombre</th><th>Año</th><th>Total KUSD</th></tr></thead><tbody>{preview.slice(0,10).map(p=><tr key={p.code}><td>{p.code}</td><td>{p.name}</td><td>{p.year}</td><td>{fmt(p.capex)}</td></tr>)}</tbody></table></div><button className="apply-import" onClick={apply}>Confirmar carga de {preview.length} proyectos</button></>}{message&&<p className="notice" role="status">{message}</p>}</section>
{view==='Resumen Ejecutivo'&&<><div className="kpi-grid">{[['CAPEX total',fmt(total)+' KUSD'],['Proyectos importados',String(projects.length)],['Presupuesto anual','Sin datos'],['Gasto real','Sin datos'],['Avance físico programado / real','Sin datos'],['Críticos / riesgo de reformulación','Sin datos']].map(([label,value])=><div className="kpi" key={label}><div>{label}</div><strong>{value}</strong><p>{label==='CAPEX total'?'Total proyecto de APIS':'Sin estimaciones ficticias'}</p></div>)}</div>{projects.length>0&&<section className="card"><h2>CAPEX por proyecto · KUSD</h2><ResponsiveContainer width="100%" height={300}><BarChart data={projects}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="code"/><YAxis/><Tooltip formatter={v=>fmt(Number(v))+' KUSD'}/><Bar dataKey="capex" name="Total proyecto" fill="#218c73"/></BarChart></ResponsiveContainer></section>}</>}
{(view==='Cartera de Proyectos'||view==='Resumen Ejecutivo')&&<section className="card"><div className="filters"><input className="search" aria-label="Buscar proyecto APIS" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar código o nombre"/><select aria-label="Área APIS" value={area} onChange={e=>setArea(e.target.value)}><option value="">Todas las áreas</option>{[...new Set(projects.map(p=>p.area))].map(a=><option key={a}>{a}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Código / nombre</th><th>Año</th><th>CAPEX KUSD</th><th>Área</th><th>Gestor</th><th>Etapa</th></tr></thead><tbody>{filtered.map(p=><tr key={p.code}><td><button className="project-link" onClick={()=>{setSelected(p.code);setView('Detalle de Proyecto');}}>{p.name}</button><small>{p.code}</small></td><td>{p.year}</td><td>{fmt(p.capex)}</td><td>{p.area}</td><td>{p.owner}</td><td>{p.stage}</td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">Carga un Excel APIS o ajusta los filtros.</p>}</div></section>}
{view==='Detalle de Proyecto'&&<section className="card"><select aria-label="Proyecto APIS" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecciona un proyecto</option>{projects.map(p=><option key={p.code} value={p.code}>{p.code} · {p.name}</option>)}</select>{project&&<><h2 className="import-help">{project.name}</h2><div className="detail-stats"><div>Código<strong>{project.code}</strong></div><div>Total proyecto<strong>{fmt(project.capex)} KUSD</strong></div><div>Año de presentación<strong>{project.year}</strong></div><div>Gestor<strong>{project.owner}</strong></div></div><dl className="project-description">{[['Tipo decisión',project.decision],['Justificación',project.justification],['Etapa',project.stage],['Área',project.area],['División',project.division],['Descripción',project.description],['Propósito',project.purpose]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Sin datos'}</dd></div>)}</dl></>}</section>}
{['Presupuesto','Avance Físico','Cronograma','Riesgos'].includes(view)&&<section className="card"><h2>Información pendiente</h2><p className="import-help">Las columnas A a L de APIS no contienen {view==='Presupuesto'?'presupuesto anual ni gasto mensual':view==='Avance Físico'?'avances físicos mensuales':view==='Cronograma'?'fechas de inicio y término':'clasificación de riesgos ni reformulación'}. Estos indicadores quedan sin datos. Para conectar CD agosto necesitamos conocer sus hojas, encabezados y unidades.</p></section>}
{projects.length>0&&<button className="apply-import" onClick={()=>{if(confirm('¿Eliminar la cartera APIS importada de esta sesión?')){sessionStorage.removeItem(key);setProjects([]);setSelected('');}}}><Trash2 size={16}/> Eliminar datos importados</button>}<footer>Modo APIS · Persistencia por sesión del navegador · Sin sincronización con Drive</footer></div></main></div>;
}
